// @ts-nocheck
/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'

const $nsid = 'agency.self.skeeditor.postVersion'

export { $nsid }

/** An archived, previous version of an edited bsky post. */
type Main = {
  $type: 'agency.self.skeeditor.postVersion'

  /**
   * The AT-URI of the original post being edited.
   */
  postUri: l.AtUriString

  /**
   * The specific CID revision of the post before this edit.
   */
  postCid?: l.CidString

  /**
   * The text of the post at this version.
   */
  text: string
  createdAt: l.DatetimeString
}

export type { Main }

/** An archived, previous version of an edited bsky post. */
const main = l.record<'tid', Main>(
  'tid',
  $nsid,
  l.object({
    postUri: l.string({ format: 'at-uri' }),
    postCid: l.optional(l.string({ format: 'cid' })),
    text: l.string(),
    createdAt: l.string({ format: 'datetime' }),
  }),
)

export { main }

export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main),
  $build = /*#__PURE__*/ main.build.bind(main),
  $type = /*#__PURE__*/ main.$type
export const $assert = /*#__PURE__*/ main.assert.bind(main),
  $check = /*#__PURE__*/ main.check.bind(main),
  $cast = /*#__PURE__*/ main.cast.bind(main),
  $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main),
  $matches = /*#__PURE__*/ main.matches.bind(main),
  $parse = /*#__PURE__*/ main.parse.bind(main),
  $safeParse = /*#__PURE__*/ main.safeParse.bind(main),
  $validate = /*#__PURE__*/ main.validate.bind(main),
  $safeValidate = /*#__PURE__*/ main.safeValidate.bind(main)
